/** Dial codes with flag emoji for phone country selector (common locales). */
export const COUNTRY_DIAL_CODES = [
    { iso: 'US', flag: '🇺🇸', dial: '+1', label: 'United States' },
    { iso: 'GB', flag: '🇬🇧', dial: '+44', label: 'United Kingdom' },
    { iso: 'IN', flag: '🇮🇳', dial: '+91', label: 'India' },
    { iso: 'AE', flag: '🇦🇪', dial: '+971', label: 'United Arab Emirates' },
    { iso: 'SA', flag: '🇸🇦', dial: '+966', label: 'Saudi Arabia' },
    { iso: 'PK', flag: '🇵🇰', dial: '+92', label: 'Pakistan' },
    { iso: 'BD', flag: '🇧🇩', dial: '+880', label: 'Bangladesh' },
    { iso: 'PH', flag: '🇵🇭', dial: '+63', label: 'Philippines' },
    { iso: 'ID', flag: '🇮🇩', dial: '+62', label: 'Indonesia' },
    { iso: 'MY', flag: '🇲🇾', dial: '+60', label: 'Malaysia' },
    { iso: 'SG', flag: '🇸🇬', dial: '+65', label: 'Singapore' },
    { iso: 'AU', flag: '🇦🇺', dial: '+61', label: 'Australia' },
    { iso: 'NZ', flag: '🇳🇿', dial: '+64', label: 'New Zealand' },
    { iso: 'DE', flag: '🇩🇪', dial: '+49', label: 'Germany' },
    { iso: 'FR', flag: '🇫🇷', dial: '+33', label: 'France' },
    { iso: 'IT', flag: '🇮🇹', dial: '+39', label: 'Italy' },
    { iso: 'ES', flag: '🇪🇸', dial: '+34', label: 'Spain' },
    { iso: 'NL', flag: '🇳🇱', dial: '+31', label: 'Netherlands' },
    { iso: 'BE', flag: '🇧🇪', dial: '+32', label: 'Belgium' },
    { iso: 'SE', flag: '🇸🇪', dial: '+46', label: 'Sweden' },
    { iso: 'NO', flag: '🇳🇴', dial: '+47', label: 'Norway' },
    { iso: 'ZA', flag: '🇿🇦', dial: '+27', label: 'South Africa' },
    { iso: 'NG', flag: '🇳🇬', dial: '+234', label: 'Nigeria' },
    { iso: 'KE', flag: '🇰🇪', dial: '+254', label: 'Kenya' },
    { iso: 'EG', flag: '🇪🇬', dial: '+20', label: 'Egypt' },
    { iso: 'BR', flag: '🇧🇷', dial: '+55', label: 'Brazil' },
    { iso: 'MX', flag: '🇲🇽', dial: '+52', label: 'Mexico' },
    { iso: 'CA', flag: '🇨🇦', dial: '+1', label: 'Canada' },
    { iso: 'JP', flag: '🇯🇵', dial: '+81', label: 'Japan' },
    { iso: 'KR', flag: '🇰🇷', dial: '+82', label: 'South Korea' },
    { iso: 'CN', flag: '🇨🇳', dial: '+86', label: 'China' },
    { iso: 'TR', flag: '🇹🇷', dial: '+90', label: 'Türkiye' },
    { iso: 'RU', flag: '🇷🇺', dial: '+7', label: 'Russia' },
    { iso: 'UA', flag: '🇺🇦', dial: '+380', label: 'Ukraine' },
    { iso: 'PL', flag: '🇵🇱', dial: '+48', label: 'Poland' },
    { iso: 'IE', flag: '🇮🇪', dial: '+353', label: 'Ireland' },
    { iso: 'PT', flag: '🇵🇹', dial: '+351', label: 'Portugal' },
];

export const DEFAULT_DIAL = COUNTRY_DIAL_CODES[0].dial;
