import { DEFAULT_DIAL } from './countryDialCodes';

export const createEmptyProfileForm = () => ({
    fullName: '',
    email: '',
    countryDial: DEFAULT_DIAL,
    phoneLocal: '',
    age: '',
    gender: '',
    familyMembers: '',
    dependents: '',
    address: '',
    latitude: '',
    longitude: '',
    medicalConditions: '',
    disabilityStatus: '',
    assistanceMedical: false,
    assistanceMobility: false,
    assistanceOther: false,
    assistanceOtherDetails: '',
    primaryEmergencyPhone: '',
    primaryEmergencyName: '',
    secondaryEmergencyPhone: '',
    secondaryEmergencyName: '',
});
